"""FastAPI REST backend — exposes the RAG pipeline as a clean API.

Start the server:
    uvicorn app.api:app --reload --port 8000

Interactive docs (auto-generated by FastAPI):
    http://localhost:8000/docs        ← Swagger UI
    http://localhost:8000/redoc       ← ReDoc

Example curl:
    curl -s -X POST http://localhost:8000/ask \\
         -H "Content-Type: application/json" \\
         -d '{"question": "How do I define a path parameter?", "mode": "reranker"}' | python -m json.tool
"""
import sys
import time
from pathlib import Path
from typing import Optional

sys.path.append(str(Path(__file__).resolve().parents[1]))

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from src import config, generate
from src.rag import RAG

# ── App ───────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Dev Docs RAG API",
    description=(
        "Retrieval-Augmented Generation over the official FastAPI documentation. "
        "Supports three retrieval strategies switchable per request: dense vector "
        "search, hybrid BM25+dense (RRF), and hybrid + cross-encoder reranker."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],      # tighten for production
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Mode registry ─────────────────────────────────────────────────────────────
MODES: dict[str, dict] = {
    "dense": {
        "use_hybrid": False,
        "use_reranker": False,
        "description": "FAISS cosine-similarity vector search only",
    },
    "hybrid": {
        "use_hybrid": True,
        "use_reranker": False,
        "description": "FAISS + BM25 keyword search fused via Reciprocal Rank Fusion",
    },
    "reranker": {
        "use_hybrid": True,
        "use_reranker": True,
        "description": "Hybrid retrieval re-scored by a cross-encoder (ms-marco-MiniLM-L-6-v2)",
    },
}

# ── Per-mode RAG cache (avoids re-loading models on every request) ─────────────
_rag_cache: dict[str, RAG] = {}

def _get_rag(mode: str) -> RAG:
    if mode not in _rag_cache:
        m = MODES[mode]
        config.USE_HYBRID   = m["use_hybrid"]
        config.USE_RERANKER = m["use_reranker"]
        _rag_cache[mode] = RAG()
    return _rag_cache[mode]


# ── Pydantic schemas ──────────────────────────────────────────────────────────
class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        examples=["How do I define a path parameter?"],
    )
    mode: str = Field(
        default="reranker",
        examples=["dense", "hybrid", "reranker"],
        description="Retrieval strategy: 'dense' | 'hybrid' | 'reranker'",
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of source chunks to retrieve",
    )


class SourceChunk(BaseModel):
    source: str = Field(description="Document filename / path")
    score:  float = Field(description="Retrieval relevance score")
    text:   str   = Field(description="Raw chunk text")


class AskResponse(BaseModel):
    question:      str
    answer:        str
    mode:          str
    top_k:         int
    hits:          list[SourceChunk]
    retrieval_ms:  float = Field(description="Time spent retrieving source chunks (ms)")
    generation_s:  float = Field(description="Time spent generating the answer (s)")


class HealthResponse(BaseModel):
    status:         str
    llm_backend:    str
    llm_model:      str
    embed_model:    str
    docs_indexed:   int
    chunks_indexed: int
    available_modes: list[str]


class ModeInfo(BaseModel):
    name:        str
    description: str


# ── Endpoints ─────────────────────────────────────────────────────────────────
@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Service health check",
    tags=["System"],
)
def health() -> HealthResponse:
    """Returns service status and loaded model info."""
    model_name = (
        config.OLLAMA_MODEL if config.LLM_BACKEND == "ollama"
        else config.HF_MODEL if config.LLM_BACKEND == "hf"
        else config.LLM_MODEL
    )
    return HealthResponse(
        status="ok",
        llm_backend=config.LLM_BACKEND,
        llm_model=model_name,
        embed_model=config.EMBEDDING_MODEL,
        docs_indexed=153,
        chunks_indexed=2208,
        available_modes=list(MODES.keys()),
    )


@app.get(
    "/modes",
    response_model=list[ModeInfo],
    summary="List retrieval modes",
    tags=["Retrieval"],
)
def list_modes() -> list[ModeInfo]:
    """Returns all available retrieval modes and their descriptions."""
    return [ModeInfo(name=k, description=v["description"]) for k, v in MODES.items()]


@app.post(
    "/ask",
    response_model=AskResponse,
    summary="Ask a question",
    tags=["RAG"],
)
def ask(req: AskRequest) -> AskResponse:
    """
    Ask any FastAPI documentation question.

    The pipeline:
    1. **Retrieve** relevant chunks using the chosen mode
    2. **Generate** a grounded answer with the configured LLM

    All answers are grounded strictly in the retrieved documentation —
    the model is instructed not to guess beyond the context.
    """
    if req.mode not in MODES:
        raise HTTPException(
            status_code=422,
            detail=f"Unknown mode '{req.mode}'. Valid options: {list(MODES.keys())}",
        )

    try:
        rag = _get_rag(req.mode)
    except Exception as exc:
        raise HTTPException(
            status_code=503,
            detail=f"Failed to initialise RAG pipeline: {exc}",
        )

    # Retrieve
    try:
        t0 = time.perf_counter()
        hits = rag.retriever.search(req.question, top_k=req.top_k)
        retrieval_ms = (time.perf_counter() - t0) * 1000
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Retrieval failed: {exc}")

    # Generate
    try:
        t1 = time.perf_counter()
        ans = generate.answer(req.question, [h["text"] for h in hits])
        generation_s = time.perf_counter() - t1
    except Exception as exc:
        raise HTTPException(
            status_code=503,
            detail=(
                f"Generation failed: {exc}. "
                f"Make sure 'ollama serve' is running and "
                f"'{config.OLLAMA_MODEL}' is pulled."
                if config.LLM_BACKEND == "ollama" else str(exc)
            ),
        )

    return AskResponse(
        question=req.question,
        answer=ans,
        mode=req.mode,
        top_k=req.top_k,
        hits=[
            SourceChunk(source=h["source"], score=round(h["score"], 4), text=h["text"])
            for h in hits
        ],
        retrieval_ms=round(retrieval_ms, 2),
        generation_s=round(generation_s, 3),
    )
